# Generated by Django 2.2.2 on 2020-05-01 05:35

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='news')),
                ('description', ckeditor.fields.RichTextField()),
                ('page_visit', models.IntegerField(default=0)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('slug', models.CharField(max_length=60, unique=True)),
                ('status', models.BooleanField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=400)),
                ('thumbup', models.IntegerField(default=0)),
                ('thumbdown', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('main_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.MainMenu')),
            ],
        ),
    ]
