# Generated by Django 2.2.2 on 2020-05-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=60), max_length=60, unique=True),
        ),
    ]
