# Generated by Django 2.2.2 on 2020-05-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20200501_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=60), max_length=60),
        ),
    ]
