# Generated by Django 2.2.2 on 2020-05-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20200502_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
