# Generated by Django 2.2.2 on 2020-05-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20200502_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
